print("Welcome to the Band Name Generator.")
city = input("What's the name of the city you grew up? ")
pet = input("What's your pet's name? ")
band_name = (city + " " + pet)
print("Your band name could be " + band_name)
